version: '3.1'

services:
  postgres:
    container_name: "postgres"
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: "${JDBC_DATABASE_URL:db}"
      POSTGRES_PASSWORD: "${JDBC_DATABASE_URL:password}" password